[project]
name = "check-xmpp-dns"
description = "Python cgi script that prints the DNS SRV records used for XMPP."
readme = "README.md"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
dnspython = "^2.7.0"
gevent = "^24.11.1"
jinja2 = "^3.1.5"
python = "^3.9.0"

[tool.poetry.group.dev.dependencies]
gunicorn = "^23.0.0"
mypy = "^1.14.0"
ruff = "^0.8.4"

[tool.ruff.lint]
extend-select = [
    "I",  # Sort imports.
]
